name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build EXE
        run: npm run dist

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: SPNATI-AP-Windows
          path: dist/*.exe
